// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"context"
	"github.com/google/go-github/v43/github"
	"github.com/shurcooL/githubv4"
	github2 "github.com/suzuki-shunsuke/renovate-issue-action/pkg/github"
	"go.uber.org/zap"
	"net/http"
)

// Injectors from wire.go:

func InitializeController(ctx context.Context, httpClient *http.Client, logCfg *zap.Config) *Controller {
	client := github.NewClient(httpClient)
	githubv4Client := githubv4.NewClient(httpClient)
	gitHub := github2.New(client, githubv4Client)
	controller := New(gitHub, logCfg)
	return controller
}
