---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**
  pull_request:
    branches: [main]
    paths:
    - .github/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
    - uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # v1.2.0
      with:
        aqua_version: v1.31.0
    - uses: suzuki-shunsuke/github-action-actionlint@764a394381fb91f87ca8a8ad022bbeb49232df8b # v0.1.2
