---
name: renovate-issue-action
on:
  pull_request:
    branches: [dummy] # TODO fix after adding renovate-issue-action to aqua-registry
    types:
    - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
    - uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # v1.2.0
      with:
        aqua_version: v1.32.0
    - run: renovate-issue-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
